### ISSUE TITLE
5.0版本服务器编译不过 Player缺少字段

### ISSUE THREAD

**Issue by pk2016** [roubingcode/ETCore#18]

**Comment by GameStartStudio** [comment]
我没遇到这个问题，你是不是选错分支了？

**Comment by pk2016** [comment]
![QQ截图20200612142021](https://user-images.githubusercontent.com/16305233/84471553-28ff4780-acb8-11ea-8acd-e262863cfd6f.png)
![QQ截图20200612142054](https://user-images.githubusercontent.com/16305233/84471564-2e5c9200-acb8-11ea-80b2-714e790da944.png)
应该没错吧

**Comment by GameStartStudio** [comment]
直接使用master分支。之前的分支是有这个问题，我master分支用了两个礼拜了，一点事都没有。
